// ============================================================
//  小吴游戏库 · 游戏数据
// ------------------------------------------------------------
//  后续补充新游戏：复制下面任意一个 { ... } 对象，粘贴到数组里，
//  改掉内容即可，页面会自动统计和展示。
//
//  字段说明：
//  id          唯一标识（英文，不要和其他游戏重复）
//  title       游戏中文名
//  subtitle    英文名 / 副标题
//  cover       封面图片路径（也可以换成真实图片，如 covers/xxx.jpg）
//  platforms   平台数组，可选值："PC" / "Switch" / "PS"
//  genre       类型标签
//  year        发行年份
//  playtime    游戏时长（小时）
//  rating      个人评分（10 分制，支持小数）
//  favorite    是否最爱（显示 ❤）
//  firstPlayed / lastPlayed  首次 / 最近游玩年份（写字符串即可，如 "2004" / "至今"）
//  status      当前状态（如：已通关 / 游玩中 / 已退坑 / 偶尔重温）
//  description 游戏介绍（卡片上会截断，弹窗里显示全文）
//  achievements 个人成就数组：icon（emoji）+ name + desc
// ============================================================

const GAMES = [
  {
    id: "cs15",
    title: "反恐精英 1.5",
    subtitle: "Counter-Strike 1.5",
    cover: "covers/cs15.jpg",
    platforms: ["PC"],
    genre: "FPS · 竞技射击",
    year: 2002,
    playtime: 800,
    rating: 9.2,
    favorite: true,
    firstPlayed: "2004",
    lastPlayed: "2008",
    status: "怀旧收藏",
    description:
      "竞技射击的启蒙之作。Dust2 的每一个拐角、每一条闪光弹的抛物线都刻在记忆里。当年放学冲进网吧，五打五、买枪、rush B，那是属于局域网和青春的枪声。",
    achievements: [
      { icon: "🎯", name: "AWP 之王", desc: "用 AWP 在单局完成 10 次爆头击杀" },
      { icon: "💣", name: "拆弹专家", desc: "累计成功拆除 100 枚 C4" },
      { icon: "🏆", name: "网吧五连冠", desc: "局域网对战拿到五连胜" },
    ],
  },
  {
    id: "red-alert",
    title: "红色警戒 2",
    subtitle: "Command & Conquer: Red Alert 2",
    cover: "covers/red-alert.jpg",
    platforms: ["PC"],
    genre: "RTS · 即时战略",
    year: 2000,
    playtime: 400,
    rating: 9.5,
    favorite: true,
    firstPlayed: "2003",
    lastPlayed: "2010",
    status: "偶尔重温",
    description:
      "「建造完毕！」「基洛夫空艇报告！」苏联的钢铁洪流、盟军的光棱坦克，共和国之辉里疯狂暴兵的快乐。和同学局域网对战到天黑的夜晚，是 RTS 的黄金时代。",
    achievements: [
      { icon: "🚁", name: "基洛夫报幕", desc: "一波 8 艘基洛夫空艇平推对手基地" },
      { icon: "🛡️", name: "钢铁洪流", desc: "20 辆天启坦克同时出击" },
      { icon: "⚡", name: "闪电翻盘", desc: "用超级武器在劣势局完成翻盘" },
    ],
  },
  {
    id: "meteor-butterfly-sword",
    title: "流星蝴蝶剑",
    subtitle: "Meteor Butterfly Sword",
    cover: "covers/meteor-butterfly-sword.jpg",
    platforms: ["PC"],
    genre: "动作 · 武侠格斗",
    year: 2002,
    playtime: 300,
    rating: 9.0,
    favorite: false,
    firstPlayed: "2005",
    lastPlayed: "2008",
    status: "已通关",
    description:
      "国产武侠动作游戏的巅峰记忆。孟星魂的连招、暗器与轻功，在网吧里和同学互相切磋「化骨绵掌」。古龙笔下的江湖，刀光剑影，快意恩仇。",
    achievements: [
      { icon: "🦋", name: "蝶舞连击", desc: "打出 30 连击不落地" },
      { icon: "🗡️", name: "快意恩仇", desc: "通关全部剧情关卡" },
      { icon: "👊", name: "化骨绵掌", desc: "徒手击败一名持械高手" },
    ],
  },
  {
    id: "botw",
    title: "塞尔达传说：旷野之息",
    subtitle: "The Legend of Zelda: Breath of the Wild",
    cover: "covers/botw.jpg",
    platforms: ["Switch"],
    genre: "开放世界 · 动作冒险",
    year: 2017,
    playtime: 145,
    rating: 9.8,
    favorite: true,
    firstPlayed: "2018",
    lastPlayed: "2020",
    status: "已通关 · 二周目",
    description:
      "Switch 时代的开放世界标杆。从初始台地纵身滑下的那一刻，海拉鲁的自由空气扑面而来。爬山、做饭、盾滑、砍树造桥，900 个呀哈哈收集到停不下来。",
    achievements: [
      { icon: "🍄", name: "海拉鲁大厨", desc: "解锁 60 种料理配方" },
      { icon: "🌰", name: "呀哈哈猎人", desc: "收集 300 颗克洛格种子" },
      { icon: "🐉", name: "逐龙者", desc: "集齐三条龙的全部素材" },
      { icon: "⚔️", name: "盖侬终结者", desc: "击败灾厄盖侬" },
    ],
  },
  {
    id: "totk",
    title: "塞尔达传说：王国之泪",
    subtitle: "The Legend of Zelda: Tears of the Kingdom",
    cover: "covers/totk.jpg",
    platforms: ["Switch"],
    genre: "开放世界 · 动作冒险",
    year: 2023,
    playtime: 165,
    rating: 9.6,
    favorite: true,
    firstPlayed: "2023",
    lastPlayed: "2024",
    status: "游玩中",
    description:
      "天空、地面、地底三层世界把「自由」进一步放大。用究极手拼出飞天摩托、用通天术穿出洞窟的瞬间——创造力就是海拉鲁最强的武器。",
    achievements: [
      { icon: "🛠️", name: "究极手", desc: "造出属于自己的飞天摩托" },
      { icon: "🕳️", name: "深渊行者", desc: "点亮地底的全部树根" },
      { icon: "🏝️", name: "天空冒险家", desc: "造访所有天空神庙" },
    ],
  },
  {
    id: "slay-the-spire",
    title: "杀戮尖塔",
    subtitle: "Slay the Spire",
    cover: "covers/slay-the-spire.jpg",
    platforms: ["PC", "Switch"],
    genre: "卡牌 · Roguelike",
    year: 2019,
    playtime: 320,
    rating: 9.3,
    favorite: false,
    firstPlayed: "2019",
    lastPlayed: "至今",
    status: "长期游玩",
    description:
      "Roguelike 卡牌构筑的开山之作。铁甲战士、沉默猎手、故障机器人、观者——每一局都是新的流派。「再来一把就睡」的结果永远是天亮。",
    achievements: [
      { icon: "🔥", name: "爬塔成瘾", desc: "累计完成 100 次攀登" },
      { icon: "⚡", name: "观者信徒", desc: "用观者击败碎片尖塔之心" },
      { icon: "💎", name: "无伤对决", desc: "无伤击败第三幕 Boss" },
    ],
  },
  {
    id: "katana-zero",
    title: "武士零",
    subtitle: "Katana ZERO",
    cover: "covers/katana-zero.jpg",
    platforms: ["PC", "Switch"],
    genre: "动作 · 平台跳跃",
    year: 2019,
    playtime: 18,
    rating: 9.4,
    favorite: false,
    firstPlayed: "2019",
    lastPlayed: "2019",
    status: "已通关",
    description:
      "赛博朋克背景下的一刀必杀。子弹时间里规划路线，出刀一气呵成，死了就重来——但每一次重来都像在拍一部霓虹色的动作电影。短小精悍的神作。",
    achievements: [
      { icon: "⚡", name: "无伤疾走", desc: "无伤通过任意一关" },
      { icon: "🔨", name: "大锤处决", desc: "用锤子完成 20 次击杀" },
      { icon: "🎭", name: "记忆迷宫", desc: "通关并理清全部剧情线索" },
    ],
  },
  {
    id: "crossfire",
    title: "穿越火线",
    subtitle: "CrossFire",
    cover: "covers/crossfire.jpg",
    platforms: ["PC"],
    genre: "FPS · 网络对战",
    year: 2008,
    playtime: 1500,
    rating: 8.6,
    favorite: false,
    firstPlayed: "2009",
    lastPlayed: "2016",
    status: "已退坑",
    description:
      "「Fire in the hole!」运输船、黑色城镇、沙漠灰，还有生化模式和挑战模式。三亿鼠标的枪战梦想，陪伴了无数个放学后的下午。",
    achievements: [
      { icon: "💥", name: "手雷艺术家", desc: "单局手雷完成三杀" },
      { icon: "🧟", name: "生化猎手", desc: "生化模式单局 50 杀" },
      { icon: "🔫", name: "运输船常客", desc: "运输船累计 500 局" },
    ],
  },
  {
    id: "league-of-legends",
    title: "英雄联盟",
    subtitle: "League of Legends",
    cover: "covers/league-of-legends.jpg",
    platforms: ["PC"],
    genre: "MOBA · 竞技对战",
    year: 2009,
    playtime: 2500,
    rating: 9.0,
    favorite: true,
    firstPlayed: "2013",
    lastPlayed: "至今",
    status: "偶尔上线",
    description:
      "「德玛西亚！」从 Faker 的劫到五杀摇滚乐队，从宿舍开黑到工作后偶尔上线。召唤师峡谷永远有下一局，五杀的快感永远都在。",
    achievements: [
      { icon: "🏆", name: "五杀时刻", desc: "拿下第一次五杀（Pentakill）" },
      { icon: "👑", name: "超神之路", desc: "单局 20 杀 0 死亡" },
      { icon: "🐉", name: "元素掌控", desc: "单局控下 4 条元素亚龙" },
    ],
  },
  {
    id: "hollow-knight",
    title: "空洞骑士",
    subtitle: "Hollow Knight",
    cover: "covers/hollow-knight.jpg",
    platforms: ["PC", "Switch"],
    genre: "类银河恶魔城 · 动作冒险",
    year: 2017,
    playtime: 58,
    rating: 9.6,
    favorite: true,
    firstPlayed: "2018",
    lastPlayed: "2021",
    status: "已通关 · 112% 完成度",
    description:
      "地下虫王国的凄美史诗。小骑士拿着骨钉一路敲碎Boss，从遗忘十字路到白宫，从泪水之城到深渊。每一个角色都有故事，每一条路都藏着秘密。「再来一个梦钉」的结果就是天亮。",
    achievements: [
      { icon: "⚔️", name: "前辈之骨钉", desc: "集齐全部骨钉升级" },
      { icon: "💀", name: "寻神者之路", desc: "击败辐光，通关神居五门" },
      { icon: "🌧️", name: "泪水之城", desc: "解锁全部地图与驿站" },
      { icon: "✨", name: "灵魂大师", desc: "无伤击败灵魂大师" },
    ],
  },
  {
    id: "hollow-knight-silksong",
    title: "空洞骑士：丝之歌",
    subtitle: "Hollow Knight: Silksong",
    cover: "covers/hollow-knight-silksong.jpg",
    platforms: ["PC", "Switch"],
    genre: "类银河恶魔城 · 动作冒险",
    year: 2025,
    playtime: 25,
    rating: 9.4,
    favorite: false,
    firstPlayed: "2025",
    lastPlayed: "至今",
    status: "游玩中",
    description:
      "大黄蜂的公主试炼。从王国边缘到苔藓之地，丝线缠绕的新地图比前作更华丽、更残酷。等了整整八年，终于等到了。",
    achievements: [
      { icon: "🧵", name: "丝线大师", desc: "解锁全部丝线技能" },
      { icon: "🗡️", name: "黄风刺", desc: "无伤击败第一个大型Boss" },
      { icon: "🏔️", name: "苔藓之地", desc: "探索全部新地图区域" },
    ],
  },
  {
    id: "buckshot-roulette",
    title: "恶魔轮盘",
    subtitle: "Buckshot Roulette",
    cover: "covers/buckshot-roulette.jpg",
    platforms: ["PC"],
    genre: "恐怖 · 策略桌游",
    year: 2023,
    playtime: 5,
    rating: 8.6,
    favorite: false,
    firstPlayed: "2024",
    lastPlayed: "2024",
    status: "已通关",
    description:
      "一局赌命的霰弹枪轮盘赌。和恶魔坐在地下室的桌前，一颗实弹、一颗空包，你不知道下一颗打在自己头上还是他头上。短小精悍的心理恐怖神作。",
    achievements: [
      { icon: "🎲", name: "赌徒本能", desc: "第一局就通关" },
      { icon: "😈", name: "恶魔终结者", desc: "无伤击败最终Boss" },
      { icon: "🍺", name: "肾上腺素", desc: "用全部道具赢下一局" },
    ],
  },
  {
    id: "dave-the-diver",
    title: "潜水员戴夫",
    subtitle: "Dave the Diver",
    cover: "covers/dave-the-diver.jpg",
    platforms: ["PC", "Switch"],
    genre: "模拟经营 · 海洋冒险",
    year: 2023,
    playtime: 38,
    rating: 9.1,
    favorite: false,
    firstPlayed: "2023",
    lastPlayed: "2024",
    status: "已通关",
    description:
      "白天潜水抓鱼，晚上开寿司店。蓝洞的海底世界比想象中还丰富，从热带鱼到巨型章鱼，从海马赛跑到海底农场。打工人戴夫的双面人生，治愈又上头。",
    achievements: [
      { icon: "🐟", name: "蓝洞鱼王", desc: "捕获全部鱼类图鉴" },
      { icon: "🍣", name: "寿司之神", desc: "店铺升到最高级" },
      { icon: "🤿", name: "深海探索者", desc: "抵达蓝洞最深处" },
    ],
  },
  {
    id: "forestrike",
    title: "预视武宗",
    subtitle: "Forestrike",
    cover: "covers/forestrike.jpg",
    platforms: ["PC", "Switch"],
    genre: "武侠 · 动作肉鸽",
    year: 2025,
    playtime: 18,
    rating: 8.8,
    favorite: false,
    firstPlayed: "2025",
    lastPlayed: "至今",
    status: "游玩中",
    description:
      "外国人做的武侠游戏，却打出了老港片的味道。阿聿的「推演」能力可以无限预演战斗，死多少次都不亏——因为每一次死亡都是在为真正的胜利铺路。",
    achievements: [
      { icon: "🥋", name: "推演宗师", desc: "不使用预演通关一场战斗" },
      { icon: "🗡️", name: "五绝传人", desc: "集齐五大宗师的全部武学" },
      { icon: "🏯", name: "救主之路", desc: "通关主线剧情" },
    ],
  },
  {
    id: "hades",
    title: "哈迪斯",
    subtitle: "Hades",
    cover: "covers/hades.jpg",
    platforms: ["PC", "Switch"],
    genre: "动作 · Roguelike",
    year: 2020,
    playtime: 95,
    rating: 9.7,
    favorite: true,
    firstPlayed: "2020",
    lastPlayed: "2023",
    status: "已通关 · 十周目",
    description:
      "逃出地狱的一百种姿势。扎格列欧斯每次死亡都在推进剧情，众神的祝福让每一局都不一样。从第一次被父亲揍到第十次通关，这不是肉鸽，这是希腊神话版的家庭伦理剧。",
    achievements: [
      { icon: "⚡", name: "奥林匹斯祝福", desc: "集齐全部神祇的祝福图鉴" },
      { icon: "👑", name: "逃离地狱", desc: "首次成功逃出冥界" },
      { icon: "🗡️", name: "热浪之巅", desc: "通关热度 32" },
      { icon: "💘", name: "众神之友", desc: "全部 NPC 好感度满级" },
    ],
  },
  {
    id: "hades-2",
    title: "哈迪斯 2",
    subtitle: "Hades II",
    cover: "covers/hades-2.jpg",
    platforms: ["PC"],
    genre: "动作 · Roguelike",
    year: 2024,
    playtime: 45,
    rating: 9.3,
    favorite: false,
    firstPlayed: "2024",
    lastPlayed: "至今",
    status: "游玩中 · 抢先体验",
    description:
      "公主殿下的弑神之路。墨利诺厄的魔法系统比哥哥的武器更华丽，时间魔法让战斗节奏完全不同。击败克洛诺斯，改写泰坦之战的结局。",
    achievements: [
      { icon: "🌙", name: "月之魔法", desc: "解锁全部魔法法术" },
      { icon: "⏳", name: "时间操控", desc: "单次冲刺中触发三次时间回溯" },
      { icon: "🏹", name: "弑神者", desc: "击败第一个主神祇" },
    ],
  },
  {
    id: "advance-wars",
    title: "高级战争",
    subtitle: "Advance Wars 1+2: Re-Boot Camp",
    cover: "covers/advance-wars.jpg",
    platforms: ["Switch"],
    genre: "战棋 · 策略模拟",
    year: 2023,
    playtime: 35,
    rating: 8.9,
    favorite: false,
    firstPlayed: "2023",
    lastPlayed: "2024",
    status: "已通关",
    description:
      "童年 GBA 战棋神作的高清重制。坦克、直升机、导弹兵，在网格地图上排兵布阵。Andy、Max、Sami——每个指挥官的技能都有不同的打法，一局能打一下午。",
    achievements: [
      { icon: "🪖", name: "战地指挥官", desc: "通关全部主线关卡" },
      { icon: "🚁", name: "空中优势", desc: "单局击毁 20 架敌方单位" },
      { icon: "⭐", name: "S 级评价", desc: "全部关卡拿到 S 级评分" },
    ],
  },
  {
    id: "dead-cells",
    title: "死亡细胞",
    subtitle: "Dead Cells",
    cover: "covers/dead-cells.jpg",
    platforms: ["PC", "Switch"],
    genre: "类银河恶魔城 · 动作肉鸽",
    year: 2018,
    playtime: 60,
    rating: 9.2,
    favorite: false,
    firstPlayed: "2018",
    lastPlayed: "2022",
    status: "偶尔重温",
    description:
      "「再来一局」的肉鸽天花板。从囚徒宿舍到巢穴，从被鞭尸到无伤通关，每一次死都是在熟悉地图。攻速流、紫水流、盾反流——Build 百变，快乐不变。",
    achievements: [
      { icon: "⚔️", name: "收藏家", desc: "解锁全部武器与技能" },
      { icon: "💀", name: "无伤之王", desc: "无伤击败国王之手" },
      { icon: "🏰", name: "地图全解锁", desc: "探索全部区域与秘密" },
    ],
  },
  {
    id: "sniper-elite-4",
    title: "狙击精英 4",
    subtitle: "Sniper Elite 4",
    cover: "covers/sniper-elite-4.jpg",
    platforms: ["PC", "PS"],
    genre: "FPS · 潜行射击",
    year: 2017,
    playtime: 22,
    rating: 8.4,
    favorite: false,
    firstPlayed: "2017",
    lastPlayed: "2019",
    status: "已通关",
    description:
      "二战意大利的狙击盛宴。从海岸村庄到山间别墅，一枪爆头的 X 光弹道慢动作永远让人上瘾。潜行绕后、利用风声掩盖枪声、一枪双杀——这才是狙击手的浪漫。",
    achievements: [
      { icon: "🎯", name: "神枪手", desc: "单局完成 10 次远程爆头" },
      { icon: "💥", name: "一枪双杀", desc: "用一发子弹贯穿两名敌人" },
      { icon: "🗺️", name: "解放意大利", desc: "通关全部战役关卡" },
    ],
  },
  {
    id: "cuphead",
    title: "茶杯头",
    subtitle: "Cuphead",
    cover: "covers/cuphead.jpg",
    platforms: ["PC", "Switch"],
    genre: "动作 · 横版射击",
    year: 2017,
    playtime: 16,
    rating: 9.0,
    favorite: false,
    firstPlayed: "2017",
    lastPlayed: "2020",
    status: "已通关",
    description:
      "1930 年代橡皮管动画风的横版 Boss 战。每一个 Boss 都是手绘帧动画，每一个弹幕 pattern 都要背。死了几十次之后终于无伤通关，那一刻的成就感无与伦比。",
    achievements: [
      { icon: "☕", name: "茶杯兄弟", desc: "通关全部主线 Boss" },
      { icon: "🏆", name: "S 级评价", desc: "全部 Boss 战拿到 S 级评分" },
      { icon: "🎵", name: "音乐大师", desc: "在音乐关卡拿到满分评价" },
    ],
  },
];
